# Generated by Django 4.2 on 2023-05-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
