# Generated by Django 4.2 on 2023-05-21 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_strories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='strories',
            old_name='footer',
            new_name='title',
        ),
        migrations.AddField(
            model_name='strories',
            name='cover_image',
            field=models.ImageField(default=datetime.datetime(2023, 5, 21, 7, 31, 50, 772718, tzinfo=datetime.timezone.utc), upload_to='strories/cover_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strories',
            name='desc',
            field=models.TextField(default=datetime.datetime(2023, 5, 21, 7, 32, 1, 716294, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strories',
            name='tag',
            field=models.ManyToManyField(related_name='strories', to='home.tag'),
        ),
    ]
