# Generated by Django 4.2 on 2023-05-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='strories',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
