# Generated by Django 4.2 on 2023-05-30 07:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_strories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strories',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
